---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
      - id: check-yaml
        exclude: molecule/default/tests/test_ca_certificates.yml
      - id: check-case-conflict
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.15.0
    hooks:
      - id: yamllint
  - repo: https://github.com/willthames/ansible-lint.git
    rev: v4.1.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: molecule/default/tests/test_ca_certificates.yml
