---
dist: trusty

env:
  matrix:
    - distro=centos version='6'
    - distro=centos version='7'
    - distro=ubuntu version='1204'
    - distro=ubuntu version='1404'
    - distro=ubuntu version='1604'
    - distro=fedora version='25'

language: ruby
cache:
  bundler: true
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

services:
  - docker

before_install:
  - pip install pre-commit

install:
  - pre-commit install
  - bundle install --without=development --binstubs=vendor/bin --path=vendor/bundle

script:
  - pre-commit run --all-files
  - vendor/bin/kitchen test ${distro}-${version}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
