---
- name: Load OS Family specific defaults
  include_vars: "defaults-{{ ansible_os_family }}.yml"

- name: Install CA Certificates package
  become: true
  package:
    name: ca-certificates
    state: present

- block:
  - name: Enable Cert Management (RHEL 6, Ansible < 2.2)
    include: ca_certificates-RedHat-6-lt-2.2.yml
    static: false
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

  - name: Install Trusted (Ansible < 2.2)
    include: ca_certificates-trusted-lt-2.2.yml
    static: false
  when: ansible_version['full'] | version_compare('2.2.0.0', operator='lt')

- block:
  - name: Enable Cert Management (RHEL 6, Ansible >= 2.2)
    include: ca_certificates-RedHat-6-ge-2.2.yml
    static: false
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

  - name: Install Trusted (Ansible >= 2.2)
    include: ca_certificates-trusted-ge-2.2.yml
    static: false
  when: ansible_version['full'] | version_compare('2.2.0.0', operator='ge')

- name: Update CA Certificates
  become: true
  command: "{{ ca_certificates_handler }}"
  when:
    - _ca_certificates_copied | changed
    - _ca_certificates_written | changed
    - ca_certificates_update | bool
